### ISSUE TITLE
Getting an error while running the playbook

### ISSUE THREAD

**Issue by Alihaider1697** [citronalco/ansible-nsupdate.info#1]
Dear Citronalco,
I am receiving the error ''FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'nsupdate' is undefined"}' whenever I run the playbook.

**Comment by Alihaider1697** [comment]
Relevant files are as follows:

nsupdate.yml file looks like this:

- hosts: nsupdate
  remote_user: root
  roles:
     - postfix
    - nginx
    - certbot
    - bind9
    - postgresql
    - nsupdate_info

host file 'hosts' looks like this:

[nsupdate]
abcdef.pk               ansible_ssh_host=101.50.x.x


Following is the complete error I am getting while running the playbook:

[root@games ansible-nsupdate.info]# ansible-playbook -i hosts nsupdate.yml

PLAY [nsupdate] **********************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************
ok: [abcdef.pk]

TASK [postfix : Install Postfix] *****************************************************************************************************************************
ok: [abcdef.pk]

TASK [postfix : Install Postfix configuration] ***************************************************************************************************************
failed: [abcdef.pk] (item={u'dest': u'/etc/postfix/main.cf', u'src': u'main.cf.j2'}) => {"ansible_loop_var": "item", "changed": false, "item": {"dest": "/etc/postfix/main.cf", "src": "main.cf.j2"}, "msg": "AnsibleUndefinedVariable: 'nsupdate' is undefined"}
ok: [abcdef.pk] => (item={u'dest': u'/etc/postfix/header_check', u'src': u'header_check.j2'})
ok: [abcdef.pk] => (item={u'dest': u'/etc/postfix/sender_canonical_maps', u'src': u'sender_canonical_maps.j2'})

PLAY RECAP ***************************************************************************************************************************************************
abcdef.pk                  : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by citronalco** [comment]
Your server is called abcdef.pk, right?
Rename host_vars/dyn.example.com to host_vars/abcdef.pk.
And have a look into that file, you'll have to change some settings according to your setup.

**Comment by Alihaider1616** [comment]
Changed Server Hostname to : ddns.nayatel.com and performed the above mentioned steps. It worked for the most part of it but receiving the following error now:

[root@games ansible-nsupdate.info]# ansible-playbook -i hosts nsupdate.yml -K
BECOME password:

PLAY [nsupdate] **********************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************
ok: [ddns.nayatel.com]

TASK [postfix : Install Postfix] *****************************************************************************************************************************
ok: [ddns.nayatel.com]

TASK [postfix : Install Postfix configuration] ***************************************************************************************************************
ok: [ddns.nayatel.com] => (item={u'dest': u'/etc/postfix/main.cf', u'src': u'main.cf.j2'})
ok: [ddns.nayatel.com] => (item={u'dest': u'/etc/postfix/header_check', u'src': u'header_check.j2'})
ok: [ddns.nayatel.com] => (item={u'dest': u'/etc/postfix/sender_canonical_maps', u'src': u'sender_canonical_maps.j2'})

TASK [postfix : Configure SASL authentication at remote SMTP server] *****************************************************************************************
ok: [ddns.nayatel.com]

TASK [Install nginx-light] ***********************************************************************************************************************************
ok: [ddns.nayatel.com]

TASK [nginx : Create nsupdate.info directory] ****************************************************************************************************************
ok: [ddns.nayatel.com]

TASK [nginx : Configure access_log anonymization] ************************************************************************************************************
ok: [ddns.nayatel.com]

TASK [Install nsupdate.info nginx site] **********************************************************************************************************************
ok: [ddns.nayatel.com]

TASK [Activate nsupdate.info nginx site] *********************************************************************************************************************
ok: [ddns.nayatel.com]

TASK [certbot : Install Certbot] *****************************************************************************************************************************
ok: [ddns.nayatel.com]

TASK [certbot : Check if certificate is already existing] ****************************************************************************************************
ok: [ddns.nayatel.com]

TASK [Stop Nginx to allow certbot to generate a cert] ********************************************************************************************************
skipping: [ddns.nayatel.com]

TASK [certbot : Generate new certificate] ********************************************************************************************************************
skipping: [ddns.nayatel.com]

TASK [certbot : Start Nginx after cert has been generated] ***************************************************************************************************
skipping: [ddns.nayatel.com]

TASK [Add hook to certbot to reload Nginx after certificate renewal] *****************************************************************************************
ok: [ddns.nayatel.com]

TASK [Install bind9] *****************************************************************************************************************************************
ok: [ddns.nayatel.com]

TASK [bind9 : Create named.conf] *****************************************************************************************************************************
ok: [ddns.nayatel.com]

TASK [bind9 : Check if config for basedomain already exists] *************************************************************************************************
ok: [ddns.nayatel.com]

TASK [bind9 : Fetch existing basedomain config file] *********************************************************************************************************
ok: [ddns.nayatel.com]

TASK [bind9 : Read current secret from existing basedomain config file] **************************************************************************************
ok: [ddns.nayatel.com]

TASK [bind9 : Create new secret] *****************************************************************************************************************************
skipping: [ddns.nayatel.com]

TASK [bind9 : Create config for basedomain] ******************************************************************************************************************
ok: [ddns.nayatel.com]

TASK [bind9 : Check if zone file for basedomain already exists] **********************************************************************************************
ok: [ddns.nayatel.com]

TASK [bind9 : Freeze existing basedomain zone file] **********************************************************************************************************
skipping: [ddns.nayatel.com]

TASK [bind9 : Fetch existing basedomain zone file] ***********************************************************************************************************
skipping: [ddns.nayatel.com]

TASK [bind9 : Read current serial from existing local zonefile] **********************************************************************************************
skipping: [ddns.nayatel.com]

TASK [bind9 : Build regex to find secondary NS in zone file] *************************************************************************************************
ok: [ddns.nayatel.com]

TASK [bind9 : Read secondary NS record from existing local zonefile] *****************************************************************************************
skipping: [ddns.nayatel.com]

TASK [bind9 : Remove secondary NS] ***************************************************************************************************************************
skipping: [ddns.nayatel.com]

TASK [bind9 : Add secondary NS] ******************************************************************************************************************************
skipping: [ddns.nayatel.com]

TASK [bind9 : Create zone file for basedomain] ***************************************************************************************************************
fatal: [ddns.nayatel.com]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'address'"}

PLAY RECAP ***************************************************************************************************************************************************
ddns.nayatel.com           : ok=20   changed=0    unreachable=0    failed=1    skipped=10   rescued=0    ignored=0

**Comment by Alihaider1616** [comment]
The error:
------------
TASK [bind9 : Create zone file for basedomain] ***************************************************************************************************************
fatal: [ddns.nayatel.com]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'address'"}

Where do I have to define this variable?

**Comment by citronalco** [comment]
The failed task creates the bind9 configuration file /var/lib/bind/ddns.nayatel.com (see roles/bind9/tasks/main.yml near the end).
Ansible does that by filling the template file roles/bind9/templates/db.basedomain.j2 with variables either set manually in host_vars/ddns.nayatel.com, or discovered automatically by Ansible from your server.

Looking in the template file, there are two variables with "address":
- ansible_default_ipv4.address
- ansible_default_ipv6.address

Both are discovered automatically by Ansible from your server.

Seems like your server has no IPv6 address?
If that's the case:
I'm not sure if nsupdate works without one, but you could try: Just comment out all lines containing "ansible_default_ipv6.address" from roles/bind9/templates/db.basedomain.j2

**Comment by Alihaider1616** [comment]
Tried it but didn't work.

db.basedomain.j2 looks like this:
-------------------------------------
; {{ ansible_managed }}

$ORIGIN .
$TTL    3600

{{ nsupdate.basedomain.name }}        IN      SOA     {{ nsupdate.basedomain.name }}. {{ nsupdate.service_contact | regex_replace('@', '.') }}. (
                                         {{ bind_serial | default(1) }} ; serial
                                      7200 ; refresh
                                      1800 ; retry
                                    604800 ; expire
                                        60 ; minimum
                                    )

                    NS      {{ nsupdate.basedomain.name }}.
{% if nsupdate.basedomain.secondary_ns.hostname is defined %}
                    NS      {{ nsupdate.basedomain.secondary_ns.hostname }}.
{% endif %}
                    A       {{ ansible_default_ipv4.address }}
#                    AAAA    {{ ansible_default_ipv6.address }}

$ORIGIN {{ nsupdate.basedomain.name }}.
$TTL    3600

www     IN      A       {{ ansible_default_ipv4.address }}
#www     IN      AAAA    {{ ansible_default_ipv6.address }}
ipv4    IN      A       {{ ansible_default_ipv4.address }}
#ipv6    IN      AAAA    {{ ansible_default_ipv6.address }}



Still receiving the same error:
--------------------------------

TASK [bind9 : Create zone file for basedomain] ***************************************************************************************************************
fatal: [ddns.nayatel.com]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'address'"}

PLAY RECAP ***************************************************************************************************************************************************
ddns.nayatel.com           : ok=20   changed=0    unreachable=0    failed=1    skipped=10   rescued=0    ignored=0

**Comment by citronalco** [comment]
Oh sorry, commenting out can't work.
Try removing those lines containing {{ ansible_default_ipv6.address }}

**Comment by Alihaider1616** [comment]
Thanks Man,
Removed the lines and it proceeded. However, receiving the following error now:
----------------

TASK [nsupdate_info : Install python dependencies] ***********************************************************************************************************
fatal: [ddns.nayatel.com]: FAILED! => {"changed": false, "msg": "Could not get output from /usr/local/bin/virtualenv --help: ModuleNotFoundError: No module named 'virtualenv.seed.via_app_data'\n"}

RUNNING HANDLER [bind9 : rndc reload] ************************************************************************************************************************

PLAY RECAP ***************************************************************************************************************************************************
ddns.nayatel.com           : ok=27   changed=6    unreachable=0    failed=1    skipped=10   rescued=0    ignored=0

**Comment by citronalco** [comment]
Never seen that before, but that does not mean too much: I'm not a Python expert.
The Internet (https://stackoverflow.com/questions/63491221/modulenotfounderror-no-module-named-virtualenv-seed-embed-via-app-data-when-i) says that you probably have already installed virtualenv via pip as root, while here it gets installed as Debian package, and having it two times causes some confusion. If that's the case `sudo pip3 uninstall virtualenv` could fix it.

While trying to reproduce your issue a few minutes ago, I've seen that a dependency has changed (would have caused an error some steps later), so I've updated this repo. So please update, too.

**Comment by citronalco** [comment]
Did it work for you, or did you give up?

**Comment by Alihaider1616** [comment]
Actually I got busy with something else. Will come back to it as soon as I get time to.

**Comment by citronalco** [comment]
Closed due to inactivity.
